load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "codechecker-bazel",
    strip_prefix = "codechecker-bazel-main",
    urls = ["https://github.com/nettle/codechecker-bazel/archive/main.tar.gz"],
)
