# # Postprocess compile_commands.json file
# py_binary(
#     name = "compile_commands_filter",
#     srcs = ["compile_commands_filter.py"],
#     visibility = ["//visibility:public"],
# )

# CodeChecker script template
exports_files(
    ["codechecker_script.py"],
)
